
# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: yolo
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
- python=3.7
- numpy
- scipy
- pylint
- pandas
- ipython
- scikit-learn
- jupyter
- matplotlib
- seaborn
- bokeh
- statsmodels
- plotly
- pytorch
- torchvision
- torchaudio
- pytorch-cuda=11.7
- pip
- pip:
  - ultralytics
